### ISSUE TITLE
New Firefox themes are interrupting my own themes

### ISSUE THREAD

**Issue by YKZarb** [drsjb80/thematic#2]
Please tell me it's possible to stop the icky new themes Firefox just forced on us with the new update from rotating through the actual ones I've chosen from my collections. Right now, there's no way to delete them permanently.

**Comment by drb80** [comment]
So I think Thematic is programmed to ignore the Alpenglow theme for rotations and it should ignore the "System theme" too. Are you seeing these in the rotation, or are there others that are installed that Thematic isn't ignoring? Thanks!

**Comment by adrianiainlam** [comment]
I think OP is referring to the "Colorways" / "Colourways" themes introduced in Firefox 94. I just upgraded and I'm seeing the same problem - 18 new themes that can't be removed.
![Screenshot from 2021-11-04 03-39-00](https://user-images.githubusercontent.com/6016750/140254204-9328ecb5-3eae-4635-a935-6fd0a2454742.png)

**Comment by SeberHusky** [comment]
Also reporting this "bug".  The Colorways themes are some rigged social media stunt Firefox pulled and its utter garbage. It's supposed to be a "limited time theme so get it while you can" they say.  These themes are hideous and awful and there is no way to delete them out of the browser. They are also screwing up my custom themes.   If anyone knows where these theme files are stored that might be the only way to stop this, or find out how to disable "Colorways".

**Comment by drb80** [comment]
Got it. I'll get ahold of 94 and make sure those themes aren't included by Thematic. I'll also see if there is a way for people to remove them.  It'll take a day or two. Thanks all!

**Comment by SeberHusky** [comment]
Good luck drb80!

**Comment by YKZarb** [comment]
> 
> 
> So I think Thematic is programmed to ignore the Alpenglow theme for rotations and it should ignore the "System theme" too. Are you seeing these in the rotation, or are there others that are installed that Thematic isn't ignoring? Thanks!

Yes. They do rotate. I hope you succeed in getting them ignored like Alpenglow and the system themes. Deleting them myself would be good too. Thank you. I'm missing my Autumn rotation!

**Comment by drb80** [comment]
Okay, I have submitted a fixed version, 7.0.5. Should be available from Mozilla soon. I put all the new themes "below the line" so they won't be included in the rotation. Once your Firefox has the new version, let me know what you think. Thanks!

**Comment by adrianiainlam** [comment]
I can confirm 7.0.5 has fixed the issue. Thanks man you rock!

**Comment by drb80** [comment]
Great! I think I can hide the new themes from the drop-down, but I'm a little torn on doing that. I'll look into putting a preference in for that.

**Comment by YKZarb** [comment]
> 
> 
> Okay, I have submitted a fixed version, 7.0.5. Should be available from Mozilla soon. I put all the new themes "below the line" so they won't be included in the rotation. Once your Firefox has the new version, let me know what you think. Thanks!

It's working now. Thank you for your help.
